export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const ADD_FIELD_SUCCESS = 'ADD_FIELD_SUCCESS';
export const ADD_FIELD_FAIL = 'ADD_FIELD_FAIL';
export const ADD_FIELD_START = 'ADD_FIELD_START';
export const ADD_INIT = 'ADD_INIT';

export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_SUCCESS';
export const DELETE_FIELD_FAIL = 'DELETE_FIELD_FAIL';
export const DELETE_FIELD_START = 'DELETE_FIELD_START';

export const FETCH_FIELDS_START = 'FETCH_FIELDS_START';
export const FETCH_FIELDS_SUCCESS = 'FETCH_FIELDS_SUCCESS';
export const FETCH_FIELDS_FAIL = 'FETCH_FIELDS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_HARVEST_SUCCESS = 'ADD_HARVEST_SUCCESS';
export const ADD_HARVEST_FAIL = 'ADD_HARVEST_FAIL';
export const ADD_HARVEST_START = 'ADD_HARVEST_START';
export const ADD_HARVEST_INIT = 'ADD_HARVEST_INIT';

export const DELETE_HARVEST_SUCCESS = 'DELETE_FIELD_SUCCESS';
export const DELETE_HARVEST_FAIL = 'DELETE_HARVEST_FAIL';
export const DELETE_HARVEST_START = 'DELETE_HARVEST_START';

export const DELETE_ALL_HARVESTS_SUCCESS = 'DELETE_ALL_HARVESTS_SUCCESS';
export const DELETE_ALL_HARVESTS_FAIL = 'DELETE_ALL_HARVESTS_FAIL';
export const DELETE_ALL_HARVESTS_START = 'DELETE_ALL_HARVESTS_START';

export const FETCH_HARVESTS_START = 'FETCH_HARVESTS_START';
export const FETCH_HARVESTS_SUCCESS = 'FETCH_HARVESTS_SUCCESS';
export const FETCH_HARVESTS_FAIL = 'FETCH_HARVESTS_FAIL';
//this is a change

//this is another change
